// In this repo i want to show the how to change the a particular html tag attribute like src, alt,placeholder etc...

let img = document.querySelector("#img");
console.log(img);
img.src = "./image1.jpg"; //Here i change the attribute of the img tag which has the ./image.jpg and change into the ./image1.jpg ...
